// The forge's words: what its smith says, and how the log names what happens.

import type { Lexicon } from '../world.ts'

export const FORGE_WORDS: Lexicon = {
  persona: 'un loup-dragon forgeron',
  helper: 'louveteau',
  placeOf: 'la forge {project}',
  lines: {
    morning: ['Bonjour, forgeron !', 'Le feu est prêt.', 'Au travail !'],
    afternoon: ['Salut, forgeron !', "L'enclume t'attend."],
    evening: ['Bonsoir, forgeron.', 'Une dernière fournée ?'],
    answer: ['Bel ouvrage !', 'Et voilà, forgé.', 'Encore une de faite.', 'Ça tient la route.', 'Au suivant !'],
    failed: ['Aïe, ça a cassé…', 'Pas cette fois.', 'Le métal résiste.', 'On remet au feu.'],
    pass: ['Belle lame !', 'Elle tient bon.', 'Trempe parfaite.'],
    crack: ['Encore fêlée…', 'La lame a cassé.', 'Retour au feu.'],
    commit: ['Scellé !', 'Caisse fermée.'],
    push: ['Vole, corbeau !', 'Livré !'],
    level: ['Niveau {n} !', 'Je progresse : niveau {n}.'],
    night: ['Il se fait tard, forgeron.', 'La lune est haute…', 'Encore une nuit à la forge.'],
    wake: ['Hein ? Je ne dormais pas !', 'Me voilà, me voilà !'],
    tea: ['Une pause, forgeron ?', 'Un thé, ça te dit ?'],
    duck: ['Bon, canard, écoute bien…', 'Le canard va m’aider.'],
    cold: ['Plus de charbon…', 'On attend la livraison.'],
    leave: ['Je passe voir {n} !', 'Un saut chez {n}.'],
    welcome: ['Bienvenue, {n} !', 'Tiens, {n} !'],
    dragon: ['Regarde, un dragon !', 'Un dragon, là, à la fenêtre !'],
    star: ['Une étoile filante !', 'Vite, fais un vœu !'],
  },
  labels: {
    idle: 'au calme',
    thinking: 'réfléchit',
    running: 'à la forge',
    review: 'inspecte',
    waiting: 'attend ton feu vert',
    failed: 'aïe…',
    jumping: 'ouvrage fini !',
    waving: 'salut !',
    quench: 'trempe la lame',
    ship: "expédie l'ouvrage",
    sweep: "balaie l'atelier",
    sleep: 'fait la sieste',
    waking: 'hein ?!',
    away: 'en visite',
  },
  atWork: {
    forge: 'à la forge',
    build: 'chauffe le fourneau',
    test: 'éprouve la lame',
    shell: 'manie ses outils',
    git: "scelle l'ouvrage",
    web: 'scrute au loin',
    agent: 'envoie un apprenti',
    mcp: 'grave une rune',
  },
  moods: {
    cold: 'à court de charbon',
    breathless: 'à bout de souffle',
    gauges: 'surveille ses jauges',
    hourglass: 'guette le sablier',
    duck: 'parle au canard',
    tea: 'prend le thé',
    yawn: 'bâille',
  },
  details: { pass: 'la lame tient', crack: 'la lame a cassé', compact: 'compacte le contexte' },
  notes: {
    look: 'tenue du jour : cape {cape}{accessory} · {temper}',
    twin: 'change de tenue : {who} portait la même',
    helperIn: 'arrivée de {name} ({type}) : {errand}',
    helperOut: '{name} rentre, mission faite',
    level: 'niveau {n} atteint',
    petIn: 'un chat-panthère entre dans la forge',
    petFrom: 'le chat-panthère arrive de chez {who}',
    petFromPlace: 'le chat-panthère arrive de la forge {project}',
    petTo: 'le chat-panthère part chez {who}',
    tripOut: 'part rendre visite à {who}',
    tripBack: 'de retour de chez {who}',
    newsDone: 'corbeau : {who} a fini sa tâche',
    newsWaiting: 'corbeau : {who} attend ton feu vert',
    guestIn: 'visite de {who}',
    guestOut: '{who} repart, et laisse {gift}',
    gifts: { coin: 'une pièce', cookie: 'un biscuit', ore: 'une pépite' },
    feast: 'banquet à la forge : tout le monde est invité',
    feastOut: 'part au banquet de {who}',
    coffee: 'un café pour commencer',
    lunch: 'casse-croûte de midi',
    lantern: 'allume la lanterne',
    testsPass: 'lame trempée : tests verts ({cmd})',
    testsFail: 'lame fêlée : tests rouges ({cmd})',
    push: 'caisse envoyée par corbeau (push)',
    commit: 'caisse scellée (commit)',
    compact: 'coup de balai : contexte compacté',
    masterpiece: "chef-d'œuvre forgé ! il a sa place d'honneur au râtelier",
    cold: 'plus de charbon : limite atteinte',
  },
  teaToast: 'deux heures de forge, une pause ?',
  today: { edits: '{n} frappes', tests: '{n} lames', builds: '{n} fournées', shells: '{n} outils', time: '{t} à la forge' },
  helpers: 'apprentis {n}',
}
