// The words a theme of one's own starts from: plain, no forge in them. A theme
// changes any of them in its `words`; whatever it leaves out is said this way.

import type { Lexicon } from '../world.ts'

export const NEUTRAL_WORDS: Lexicon = {
  persona: 'un petit personnage qui aide au code',
  helper: 'assistant',
  placeOf: "l'atelier {project}",
  lines: {
    morning: ['Bonjour !', 'Au travail !'],
    afternoon: ['Salut !', 'On s’y remet ?'],
    evening: ['Bonsoir.', 'Encore un peu ?'],
    answer: ['Et voilà !', 'Bel ouvrage !', 'Au suivant !', 'Une de faite.'],
    failed: ['Aïe…', 'Pas cette fois.', 'On réessaie.'],
    pass: ['Tests verts !', 'Ça tient !'],
    crack: ['Tests rouges…', 'Encore raté.'],
    commit: ['Enregistré !'],
    push: ['Envoyé !'],
    level: ['Niveau {n} !', 'Je progresse : niveau {n}.'],
    night: ['Il se fait tard…', 'Encore une nuit de travail.'],
    wake: ['Hein ? Je ne dormais pas !', 'Me voilà !'],
    tea: ['Une pause ?', 'Un thé, ça te dit ?'],
    duck: ['Bon, canard, écoute bien…'],
    cold: ['Plus d’énergie…', 'On attend la recharge.'],
    leave: ['Je passe voir {n} !'],
    welcome: ['Bienvenue, {n} !', 'Tiens, {n} !'],
    dragon: ['Regarde, un dragon !'],
    star: ['Une étoile filante !', 'Vite, fais un vœu !'],
  },
  labels: {
    idle: 'au calme',
    thinking: 'réfléchit',
    running: 'au travail',
    review: 'examine',
    waiting: 'attend ton feu vert',
    failed: 'aïe…',
    jumping: "c'est fini !",
    waving: 'salut !',
    quench: 'vérifie les tests',
    ship: 'envoie le travail',
    sweep: 'range',
    sleep: 'fait la sieste',
    waking: 'hein ?!',
    away: 'en visite',
  },
  atWork: {
    forge: 'écrit',
    build: 'compile',
    test: 'teste',
    shell: 'lance une commande',
    git: 'enregistre',
    web: 'cherche au loin',
    agent: 'envoie un assistant',
    mcp: 'utilise un outil',
  },
  moods: {
    cold: "à court d'énergie",
    breathless: 'à bout de souffle',
    gauges: 'surveille ses jauges',
    hourglass: 'attend une commande',
    duck: 'parle au canard',
    tea: 'prend le thé',
    yawn: 'bâille',
  },
  details: { pass: 'tests verts', crack: 'tests rouges', compact: 'compacte le contexte' },
  notes: {
    look: 'tenue du jour : {cape}{accessory} · {temper}',
    twin: 'change de tenue : {who} portait la même',
    helperIn: 'arrivée de {name} ({type}) : {errand}',
    helperOut: '{name} a fini sa mission',
    level: 'niveau {n} atteint',
    petIn: "un chat entre dans l'atelier",
    petFrom: 'le chat arrive de chez {who}',
    petFromPlace: "le chat arrive de l'atelier {project}",
    petTo: 'le chat part chez {who}',
    tripOut: 'part rendre visite à {who}',
    tripBack: 'de retour de chez {who}',
    newsDone: 'messager : {who} a fini sa tâche',
    newsWaiting: 'messager : {who} attend ton feu vert',
    guestIn: 'visite de {who}',
    guestOut: '{who} repart, et laisse {gift}',
    gifts: { coin: 'une pièce', cookie: 'un biscuit', ore: 'un caillou brillant' },
    feast: "fête à l'atelier : tout le monde est invité",
    feastOut: 'part à la fête de {who}',
    coffee: 'un café pour commencer',
    lunch: 'casse-croûte de midi',
    lantern: 'allume la lumière',
    testsPass: 'tests verts ({cmd})',
    testsFail: 'tests rouges ({cmd})',
    push: 'travail envoyé (push)',
    commit: 'travail enregistré (commit)',
    compact: 'coup de balai : contexte compacté',
    masterpiece: "chef-d'œuvre : une longue tâche finie avec des tests verts",
    cold: "plus d'énergie : limite atteinte",
  },
  teaToast: 'deux heures de travail, une pause ?',
  today: { edits: '{n} retouches', tests: '{n} tests', builds: '{n} compilations', shells: '{n} commandes', time: '{t} au travail' },
  helpers: 'assistants {n}',
}
